### ISSUE TITLE
pip install fails with FileNotFoundError

### ISSUE THREAD

**Issue by ThomastheBicyclist** [PiotrDabkowski/Js2Py#10]
```python
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-qfdeesuo/js2py/setup.py", line 14, in <module>
        long_description=open('README.rst', 'rt').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-qfdeesuo/js2py
```

Pip and setuptools are all up to date. 

Perhaps I have something else set up wrong?

**Comment by PiotrDabkowski** [comment]
This was my fault. Please try it now.

**Comment by ThomastheBicyclist** [comment]
Success, thank you!
