### ISSUE TITLE
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function

### ISSUE THREAD

**Issue by derjasper** [PiotrDabkowski/Js2Py#117]
After translating `JSDOMParser.js` from [Readability.js](https://github.com/mozilla/readability) using 

`js2py.translate_file('readability/JSDOMParser.js', 'out/JSDOMParser.py')`

and importing the resulting file in python using

`import JSDOMParser`

the following error is thrown:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jasper/Dokumente/Projekte/NewsAggregator/python-Readability.js/out/JSDOMParser.py", line 939, in <module>
    PyJs_anonymous_0_(var.get(u"this"))
  File "/home/jasper/.local/lib/python3.5/site-packages/js2py/base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "/home/jasper/.local/lib/python3.5/site-packages/js2py/base.py", line 1344, in call
    return Js(self.code(*args))
  File "/home/jasper/Dokumente/Projekte/NewsAggregator/python-Readability.js/out/JSDOMParser.py", line 717, in PyJs_anonymous_0_
    PyJs_anonymous_62_(var.get('styleMap').get(var.get('jsName')))
  File "/home/jasper/.local/lib/python3.5/site-packages/js2py/base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "/home/jasper/.local/lib/python3.5/site-packages/js2py/base.py", line 1344, in call
    return Js(self.code(*args))
  File "/home/jasper/Dokumente/Projekte/NewsAggregator/python-Readability.js/out/JSDOMParser.py", line 708, in PyJs_anonymous_62_
    var.get('Style').get('prototype').callprop('__defineGetter__', var.get('jsName'), PyJs_anonymous_63_)
  File "/home/jasper/.local/lib/python3.5/site-packages/js2py/base.py", line 938, in callprop
    raise  MakeError('TypeError','%s is not a function'%cand.typeof())
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function
```

Am I using the library wrong or is it a bug?

**Comment by PiotrDabkowski** [comment]
You can see that the error is caused by the readability using the method `__defineGetter__` which is not a part of any specification as explained [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__). Also it seems that this library is specifically designed for the browser environment so it will not work with standard JS implementation.
