### ISSUE TITLE
Crash when checking if String.replace accepts a function as a replacement value

### ISSUE THREAD

**Issue by worstperson** [PiotrDabkowski/Js2Py#16]
Here is the test code:

import js2py
t = r'''function test() { if (!''.replace(/^/, String)) { console.log("passed!"); };}'''
js2py.eval_js(t)()

And the trace:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print js2py.eval_js(t)()
  File "/home/anon/Projects/libvid/js2py/base.py", line 999, in __call__
    return to_python(parent._obj.callprop(meth, *args))
  File "/home/anon/Projects/libvid/js2py/base.py", line 821, in callprop
    return cand.call(self, args)
  File "/home/anon/Projects/libvid/js2py/base.py", line 1191, in call
    return Js(self.code(*args))
  File "<string>", line 6, in PyJsHoisted_test_
  File "/home/anon/Projects/libvid/js2py/base.py", line 821, in callprop
    return cand.call(self, args)
  File "/home/anon/Projects/libvid/js2py/base.py", line 1191, in call
    return Js(self.code(*args))
  File "/home/anon/Projects/libvid/js2py/prototypes/jsstring.py", line 191, in replace
    args = tuple(this.Js(x) for x in args)
  File "/home/anon/Projects/libvid/js2py/prototypes/jsstring.py", line 191, in <genexpr>
    args = tuple(this.Js(x) for x in args)
NameError: global name 'this' is not defined

This check is most commonly used with packer http://dean.edwards.name/packer/ with Base62 encoding enabled. It runs correctly if I remove the check and optimised code, but crashes again if I remove the check and fallback code. Packer without Base62 does not work due to lack of radix support for Number.toString, but works fine otherwise.

**Comment by PiotrDabkowski** [comment]
File "/home/anon/Projects/libvid/js2py/prototypes/jsstring.py", line 191:
change this line to:

    args = tuple([this.Js(x) for x in args])

and it will work fine (its rather hard to explain why but its because of my bytecode modification which does not support generators :)  ). I will add support for radix tomorrow.

**Comment by worstperson** [comment]
Your fix worked perfectly, thank you!
