### ISSUE TITLE
Python 3.8 Support 

### ISSUE THREAD

**Issue by SmartManoj** [PiotrDabkowski/Js2Py#175]
```
Traceback (most recent call last):
  File "D:\1.Manoj\4.Study\4.Codes\p.py", line 5, in <module>
    import js2py
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python38\lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python38\lib\site-packages\js2py\base.py", line 2798, in <module>
    FunctionPrototype = PyJsFunction(Empty, ObjectPrototype)
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python38\lib\site-packages\js2py\base.py", line 1376, in __init__
    cand = fix_js_args(func)
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python38\lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
  File "C:\Users\Smart\AppData\Local\Programs\Python\Python38\lib\site-packages\js2py\utils\injector.py", line 120, in append_arguments
    return types.CodeType(*args)
TypeError: an integer is required (got type bytes)
```

**Comment by PiotrDabkowski** [comment]
Thanks for reporting!
This is due to the bytecode change: https://docs.python.org/3.8/whatsnew/3.8.html#cpython-bytecode-changes
Python 3.8 will not work with Js2Py until I adjust the bytecode modification, this may take some time as I am currently quite busy.
If anybody wants to give it a go, the `js2py\utils\injector.py` needs to be modified to support 3.8.

**Comment by PetterS** [comment]
Just noticed this as well and it turned out to be easy to fix. See PR.

**Comment by PetterS** [comment]
Why did you close this issue? It is not fixed until the PR is merged.

**Comment by SmartManoj** [comment]
@PetterS I think the PR is enough.
