### ISSUE TITLE
RuntimeError: No lval found "PyJs_anonymous_1_" (0.63 to 0.66 regression)

### ISSUE THREAD

**Issue by brechtm** [PiotrDabkowski/Js2Py#178]
```
PyJs_anonymous_1_
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/brechtm/Documents/Code/structed/venv/lib/python3.7/site-packages/js2py/evaljs.py", line 75, in translate_file
    py_code = translate_js(js)
  File "/Users/brechtm/Documents/Code/structed/venv/lib/python3.7/site-packages/js2py/translators/translator.py", line 70, in translate_js
    parsed)  # syntax tree to python code
  File "/Users/brechtm/Documents/Code/structed/venv/lib/python3.7/site-packages/js2py/translators/translating_nodes.py", line 121, in trans
    return node(**ele)
  File "/Users/brechtm/Documents/Code/structed/venv/lib/python3.7/site-packages/js2py/translators/translating_nodes.py", line 563, in Program
    code = inline_stack.inject_inlines(code)
  File "/Users/brechtm/Documents/Code/structed/venv/lib/python3.7/site-packages/js2py/translators/translating_nodes.py", line 48, in inject_inlines
    source = inject_before_lval(source, lval, self.reps[lval])
  File "/Users/brechtm/Documents/Code/structed/venv/lib/python3.7/site-packages/js2py/translators/friendly_nodes.py", line 33, in inject_before_lval
    raise RuntimeError('No lval found "%s"' % lval)
RuntimeError: No lval found "PyJs_anonymous_1_"
```

Let me know if I can provide anything to help debug this.

Thanks for building this awesome project!

**Comment by cyberjamus** [comment]
Same here:
PyJs_anonymous_150_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\apps\Python3913\lib\site-packages\js2py\evaljs.py", line 75, in translate_file
    py_code = translate_js6(js)
  File "C:\apps\Python3913\lib\site-packages\js2py\evaljs.py", line 125, in translate_js6
    return translate_js(js6_to_js5(js))
  File "C:\apps\Python3913\lib\site-packages\js2py\translators\translator.py", line 72, in translate_js
    return HEADER + translating_nodes.trans(
  File "C:\apps\Python3913\lib\site-packages\js2py\translators\translating_nodes.py", line 139, in trans
    return node(**ele)
  File "C:\apps\Python3913\lib\site-packages\js2py\translators\translating_nodes.py", line 599, in Program
    code = inline_stack.inject_inlines(code)
  File "C:\apps\Python3913\lib\site-packages\js2py\translators\translating_nodes.py", line 58, in inject_inlines
    source = inject_before_lval(source, lval, self.reps[lval])
  File "C:\apps\Python3913\lib\site-packages\js2py\translators\friendly_nodes.py", line 33, in inject_before_lval
    raise RuntimeError('No lval found "%s"' % lval)
RuntimeError: No lval found "PyJs_anonymous_150_"
