### ISSUE TITLE
js2py.test_internals fails

### ISSUE THREAD

**Issue by wiene** [PiotrDabkowski/Js2Py#185]
For me `js2py.test_internals` fails:
```
ImportError: Failed to import test module: js2py.test_internals
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_js2py/build/js2py/test_internals.py", line 9, in <module>
    print(seval.eval_js_vm(x))
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_js2py/build/internals/seval.py", line 33, in eval_js_vm
    return a.exe.run(a.exe.space.GlobalObj)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_js2py/build/internals/code.py", line 190, in run
    status = self.tape[loc].eval(ctx)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_js2py/build/internals/opcodes.py", line 350, in eval
    ctx.stack.append(ctx.get(self.identifier, throw=True))
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_js2py/build/internals/base.py", line 744, in get
    return self.prototype.get(var, throw)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_js2py/build/internals/base.py", line 752, in get
    raise MakeError('ReferenceError', '%s is not defined' % var)
internals.simplex.JsException: ReferenceError: h123 is not defined
```
Any idea what goes wrong here?

**Comment by wiene** [comment]
This issue is probably related to #98 and #159.
