### ISSUE TITLE
SyntaxError with escaped quote

### ISSUE THREAD

**Issue by kspeeckaert** [PiotrDabkowski/Js2Py#204]
The issue seems to be with the escaped single quotes (`\'`) . If you remove them, the parsing is successful.

Version info:

- Python 3.7.7 on Mac OS X 10.15.4
- Js2Py: 0.70

Example code:

```python
js_script = """
	dataLayer = [{
		'event': 'detailview',
		'page': {
			'phase': 'interest',
		},
		'ecommerce': {
			'detail': {
				'products': [{
				'name': 'L\'eau d\'issey eau de toilette vapo men',
				'id': '1070932',
				'price': '41.69',
				'category': '',
				'brand': 'Issey',
				'quantity': 1,
				'dimension01': ''
				}]
			}
		}
	}];
"""
js_data = js2py.eval_js(js_script)

>>> JsException: SyntaxError: Line 10: Unexpected identifier
```

**Comment by mgrela** [comment]
This is still an issue in git HEAD:

```
(generic) ➜  ~ pip install git+https://github.com/PiotrDabkowski/Js2Py.git
Collecting git+https://github.com/PiotrDabkowski/Js2Py.git
  Cloning https://github.com/PiotrDabkowski/Js2Py.git to /private/var/folders/11/kk1npt454pv3vjxb3_9b7cqc0000gp/T/pip-req-build-if448rz3
  Running command git clone -q https://github.com/PiotrDabkowski/Js2Py.git /private/var/folders/11/kk1npt454pv3vjxb3_9b7cqc0000gp/T/pip-req-build-if448rz3
Requirement already satisfied (use --upgrade to upgrade): Js2Py==0.70 from git+https://github.com/PiotrDabkowski/Js2Py.git in ./venvs/generic/lib/python3.7/site-packages
Requirement already satisfied: tzlocal>=1.2 in ./venvs/generic/lib/python3.7/site-packages (from Js2Py==0.70) (2.1)
Requirement already satisfied: six>=1.10 in ./venvs/generic/lib/python3.7/site-packages (from Js2Py==0.70) (1.13.0)
Requirement already satisfied: pyjsparser>=2.5.1 in ./venvs/generic/lib/python3.7/site-packages (from Js2Py==0.70) (2.7.1)
Requirement already satisfied: pytz in ./venvs/generic/lib/python3.7/site-packages (from tzlocal>=1.2->Js2Py==0.70) (2020.1)
Could not build wheels for Js2Py, since package 'wheel' is not installed.
Could not build wheels for tzlocal, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for pyjsparser, since package 'wheel' is not installed.
Could not build wheels for pytz, since package 'wheel' is not installed.
(generic) ➜  ~ python3                                                    
Python 3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import js2py
>>> js2py.eval_js("var a = 'hello \' world'; a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/js2py/evaljs.py", line 115, in eval_js
    return e.eval(js)
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/js2py/evaljs.py", line 204, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/js2py/evaljs.py", line 199, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 2, in <module>
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/js2py/host/jseval.py", line 17, in Eval
    py_code = translate_js(code.to_string().value, '')
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/js2py/translators/translator.py", line 65, in translate_js
    parsed = parser.parse(js)  # js to esprima syntax tree
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 3008, in parse
    program = self.parseProgram()
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 2974, in parseProgram
    body = self.parseScriptBody()
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 2963, in parseScriptBody
    statement = self.parseStatementListItem()
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 2110, in parseStatementListItem
    return self.parseStatement()
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 2699, in parseStatement
    return self.parseVariableStatement(node)
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 2191, in parseVariableStatement
    self.consumeSemicolon()
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 1120, in consumeSemicolon
    self.throwUnexpectedToken(self.lookahead)
  File "/Users/maciej.grela/venvs/generic/lib/python3.7/site-packages/pyjsparser/parser.py", line 1046, in throwUnexpectedToken
    raise self.unexpectedTokenError(token, message)
js2py.internals.simplex.JsException: SyntaxError: Line 1: Unexpected identifier
>>> 
```

**Comment by PiotrDabkowski** [comment]
This is not an issue, OP closed it because he realised his mistake. Just remember to use raw strings.
```python
>>> """var x = {'name': 'L\'eau d\'issey eau de toilette vapo men',};"""
"var x = {'name': 'L'eau d'issey eau de toilette vapo men',};"
```
As you can see the escapes are removed and JS cannot see them anymore, you need one escape for python literal and one for javascript literal.
```python
>>> js2py.eval_js(r"""var x = {'name': 'L\'eau d\'issey eau de toilette vapo men',};""")
```
works just fine.
