### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by acrogenesis** [PiotrDabkowski/Js2Py#205]
I'm trying to import a library and after install I get an `SyntaxError: invalid syntax` error. I've tried with python 3.8 and 3.7
```
>>> js2py.require('tiktok-api')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/acrogenesis/.local/share/virtualenvs/tiktok-api-MWORgHpC/lib/python3.7/site-packages/js2py/node_import.py", line 161, in require
    exec(py_code, context)
  File "<string>", line 2172
    var.put('i', (var.get('sd')-var.get('d')))
      ^
SyntaxError: invalid syntax
```

**Comment by PiotrDabkowski** [comment]
I have fixed this at head. At least now it compiles:
```python
>>> js2py.require("tiktok-api", update=True).getRequestParams()
{'ac': 'wifi', 'aid': '1233', 'app_language': 'en', 'app_name': 'musical_ly', 'build_number': '9.1.0', 'carrier_region': 'AU', 'carrier_region_v2': '505', 'channel': 'googleplay', 'device_brand': 'Google', 'device_platform': 'android', 'device_type': 'Pixel', 'dpi': 420, 'is_my_cn': 0, 'language': 'en', 'manifest_version_code': '2018111632', 'mcc_mnc': '', 'os_api': '23', 'os_version': '7.1.2', 'pass-region': 1, 'pass-route': 1, 'region': 'US', 'resolution': '1080*1920', 'ssmix': 'a', 'sys_region': 'US', 'timezone_name': 'Australia/Brisbane', 'timezone_offset': 36000, 'update_version_code': '2018111632', 'version_code': 910, 'version_name': '9.1.0'}
```
Note, this module may not work if it depends on Node environment (eg to issue requests).

For the record the issue was caused by labeled statement pretending to be a loop, this is definitely one of the ugliest functions I have seen in some time:

```js
/*
 * Round x to sd significant digits using rounding mode rm. Check for over/under-flow.
 * If r is truthy, it is known that there are more digits after the rounding digit.
 */
function round(x, sd, rm, r) {
    var d,
        i,
        j,
        k,
        n,
        ni,
        rd,
        xc = x.c,
        pows10 = POWS_TEN;

    // if x is not Infinity or NaN...
    if (xc) {

        // rd is the rounding digit, i.e. the digit after the digit that may be rounded up.
        // n is a base 1e14 number, the value of the element of array x.c containing rd.
        // ni is the index of n within x.c.
        // d is the number of digits of n.
        // i is the index of rd within n including leading zeros.
        // j is the actual index of rd within n (if < 0, rd is a leading zero).
        out: {

            // Get the number of digits of the first element of xc.
            for (d = 1, k = xc[0]; k >= 10; k /= 10, d++) {
            }
            i = sd - d;

            // If the rounding digit is in the first element of xc...
            if (i < 0) {
                i += LOG_BASE;
                j = sd;
                n = xc[ni = 0];

                // Get the rounding digit at index j of n.
                rd = n / pows10[d - j - 1] % 10 | 0;
            } else {
                ni = mathceil((i + 1) / LOG_BASE);

                if (ni >= xc.length) {

                    if (r) {

                        // Needed by sqrt.
                        for (; xc.length <= ni; xc.push(0)) {
                        }
                        n = rd = 0;
                        d = 1;
                        i %= LOG_BASE;
                        j = i - LOG_BASE + 1;
                    } else {
                        break out;
                    }
                } else {
                    n = k = xc[ni];

                    // Get the number of digits of n.
                    for (d = 1; k >= 10; k /= 10, d++) {
                    }

                    // Get the index of rd within n.
                    i %= LOG_BASE;

                    // Get the index of rd within n, adjusted for leading zeros.
                    // The number of leading zeros of n is given by LOG_BASE - d.
                    j = i - LOG_BASE + d;

                    // Get the rounding digit at index j of n.
                    rd = j < 0 ? 0 : n / pows10[d - j - 1] % 10 | 0;
                }
            }

            r = r || sd < 0 ||

                // Are there any non-zero digits after the rounding digit?
                // The expression  n % pows10[d - j - 1]  returns all digits of n to the right
                // of the digit at j, e.g. if n is 908714 and j is 2, the expression gives 714.
                xc[ni + 1] != null || (j < 0 ? n : n % pows10[d - j - 1]);

            r = rm < 4 ? (rd || r) && (rm == 0 || rm == (x.s < 0 ? 3 : 2)) : rd > 5 || rd == 5 && (rm == 4 || r || rm == 6 &&

                // Check whether the digit to the left of the rounding digit is odd.
                (i > 0 ? j > 0 ? n / pows10[d - j] : 0 : xc[ni - 1]) % 10 & 1 || rm == (x.s < 0 ? 8 : 7));

            if (sd < 1 || !xc[0]) {
                xc.length = 0;

                if (r) {

                    // Convert sd to decimal places.
                    sd -= x.e + 1;

                    // 1, 0.1, 0.01, 0.001, 0.0001 etc.
                    xc[0] = pows10[(LOG_BASE - sd % LOG_BASE) % LOG_BASE];
                    x.e = -sd || 0;
                } else {

                    // Zero.
                    xc[0] = x.e = 0;
                }

                return x;
            }

            // Remove excess digits.
            if (i == 0) {
                xc.length = ni;
                k = 1;
                ni--;
            } else {
                xc.length = ni + 1;
                k = pows10[LOG_BASE - i];

                // E.g. 56700 becomes 56000 if 7 is the rounding digit.
                // j > 0 means i > number of leading zeros of n.
                xc[ni] = j > 0 ? mathfloor(n / pows10[d - j] % pows10[j]) * k : 0;
            }

            // Round up?
            if (r) {

                for (; ;) {

                    // If the digit to be rounded up is in the first element of xc...
                    if (ni == 0) {

                        // i will be the length of xc[0] before k is added.
                        for (i = 1, j = xc[0]; j >= 10; j /= 10, i++) {
                        }
                        j = xc[0] += k;
                        for (k = 1; j >= 10; j /= 10, k++) {
                        }

                        // if i != k the length has increased.
                        if (i != k) {
                            x.e++;
                            if (xc[0] == BASE) xc[0] = 1;
                        }

                        break;
                    } else {
                        xc[ni] += k;
                        if (xc[ni] != BASE) break;
                        xc[ni--] = 0;
                        k = 1;
                    }
                }
            }

            // Remove trailing zeros.
            for (i = xc.length; xc[--i] === 0; xc.pop()) {
            }
        }

        // Overflow? Infinity.
        if (x.e > MAX_EXP) {
            x.c = x.e = null;

            // Underflow? Zero.
        } else if (x.e < MIN_EXP) {
            x.c = [x.e = 0];
        }
    }

    return x;
}
```

The translated Python file is 20k lines of code.
