### ISSUE TITLE
Unable to import js2py

### ISSUE THREAD

**Issue by avimehanwal** [PiotrDabkowski/Js2Py#21]
After cloning the package and adding its path in sys.path I am not able to import the library.
```
>>> import Js2Py.js2py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Js2Py/js2py/__init__.py", line 67, in <module>
    from js2py.evaljs import *
ImportError: No module named 'js2py'
>>> sys.path.append('/Users/Js2Py')
>>> import js2py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Js2Py/js2py/__init__.py", line 67, in <module>
    from js2py.evaljs import *
  File "/Users/Js2Py/js2py/evaljs.py", line 56
    exec DEFAULT_HEADER in self._context
                      ^
SyntaxError: Missing parentheses in call to 'exec'
>>> 

```
operated on python3.4 on Mac

**Comment by avimehanwal** [comment]
Git it ! Works for python2.7
Maybe its not python3.x compliant thats why :)

**Comment by avimehanwal** [comment]
Oops !! but Still doesn't works
```
>>> c = js2py.eval_js(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Js2Py/js2py/evaljs.py", line 39, in eval_js
    e = EvalJs()
  File "/Users/js2py/evaljs.py", line 56, in __init__
    exec DEFAULT_HEADER in self._context
  File "<string>", line 1, in <module>
  File "/Users/Js2Py/js2py/pyjs.py", line 3, in <module>
    from constructors.jsdate import Date
  File "/Users/Js2Py/js2py/constructors/jsdate.py", line 2, in <module>
    from time_helpers import *
  File "/Users/Js2Py/js2py/constructors/time_helpers.py", line 4, in <module>
    from tzlocal import get_localzone
ImportError: No module named tzlocal
>>> 
```

**Comment by PiotrDabkowski** [comment]
You have to install tzlocal. Did you install Js2Py using pip? It should be installed automatically. pip install tzlocal

**Comment by PiotrDabkowski** [comment]
And you are right - python 3 is not supported

**Comment by avimehanwal** [comment]
Nopes ! I didn't try with pip
I tried by cloning the repo. Let me try via pip

**Comment by liz282907** [comment]
not working ...python 2.7 in mac
![image](https://cloud.githubusercontent.com/assets/11833779/26751742/6035431e-4873-11e7-8109-c5c10233edd2.png)

**Comment by PiotrDabkowski** [comment]
It's not because of the Js2Py. You can clearly see in the error message that the library `six` fails to install. Try `pip install --ignore-installed six` and later `pip install js2py`.

**Comment by saltnpixels** [comment]
I tried installing any module missing and it says:

```
 Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ericgreenfield/Documents/PhoenixBot/env/bin/python3 /Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/tmp91230bbx
         cwd: /private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-install-ehgo3bhi/pyqt5
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 82, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 479, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 64, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 89, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 225, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/private/var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/pip-build-env-jccoyerw/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 68, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ericgreenfield/Documents/PhoenixBot/env/bin/python3 /Users/ericgreenfield/Documents/PhoenixBot/env/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/c9/pp416cp12xd0nx48hsz2bh_c0000gn/T/tmp91230bbx Check the logs for full command output.
```
