### ISSUE TITLE
Error with pyinstaller.

### ISSUE THREAD

**Issue by taoz27** [PiotrDabkowski/Js2Py#244]

**Comment by taoz27** [comment]
Traceback (most recent call last):
  File "test.py", line 166, in <module>
    CryptoJS = js2py.require('crypto-js')
  File "js2py\node_import.py", line 155, in require
  File "js2py\node_import.py", line 77, in _get_and_translate_npm_module
  File "js2py\node_import.py", line 20, in _init
AssertionError: You must have node installed! run: brew install node
[13296] Failed to execute script test
