### ISSUE TITLE
Python 3.11: RuntimeError: Your python version made changes to the bytecode

### ISSUE THREAD

**Issue by The-Compiler** [PiotrDabkowski/Js2Py#282]
With Python 3.11.0a7, `import js2py` results in:

```pytb
b'\x97\x00|\x00j\x00}\x01t\x03t\x05|\x00\xa6\x01\xab\x01\xa6\x01\xab\x01}\x02i\x00}\x03g\x00}\x04|\x02D\x00]A}\x05|\x05|\x03t\x07|\x04\xa6\x01\xab\x01<\x00|\x04\xa0\x04t\x0b|\x05j\x06|\x05j\x07\xa6\x02\xab\x02\xa6\x01\xab\x01\x01\x00\x8cBt\x10j\tr\x8ed\x01\xa0\n|\x04\xa6\x01\xab\x01}\x06n\x0ft\x17|\x04\xa6\x01\xab\x01}\x06|\x06|\x01k\x03\x90\x01r\xact\x19|\x06\xa6\x01\xab\x01\x01\x00t\x19|\x01\xa6\x01\xab\x01\x01\x00t\x1bt\x1dt\x07|\x06\xa6\x01\xab\x01t\x07|\x01\xa6\x01\xab\x01\xa6\x02\xab\x02\xa6\x01\xab\x01D\x00]\xb4}\x07|\x01|\x07\x19\x00|\x06|\x07\x19\x00k\x03\x90\x01r\x9d\t\x00|\x07|\x03v\x00\x90\x01r\x9ct\x19|\x03|\x07\x19\x00\xa6\x01\xab\x01\x01\x00t\x19|\x03|\x07d\x03z\n\x19\x00\xa6\x01\xab\x01\x01\x00t\x19t\x03t\x1ft |\x01\xa6\x02\xab\x02\xa6\x01\xab\x01|\x07d\x04z\n|\x07d\x05z\x00\x85\x02\x19\x00\xa6\x01\xab\x01\x01\x00t\x19|\x04|\x07d\x04z\n|\x07d\x05z\x00\x85\x02\x19\x00\xa6\x01\xab\x01\x01\x00n\x01\x8c\x8et#d\x06\xa6\x01\xab\x01\x82\x01d\x00S\x00d\x00S\x00'
b'\x97\x00|\x00j\x00\x00\x00\x00\x00\x00\x00\x00\x00}\x01t\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x02i\x00}\x03g\x00}\x04|\x02D\x00]A}\x05|\x05|\x03t\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00|\x04\xa0\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x05j\x06\x00\x00\x00\x00\x00\x00\x00\x00|\x05j\x07\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x8cBt\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\t\x00\x00\x00\x00\x00\x00\x00\x00r\x8ed\x01\xa0\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x06n\x0ft\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x06|\x06|\x01k\x03\x00\x00\x00\x00\x90\x01r\xact\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x06\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x1b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x1d\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x06\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00t\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00D\x00]\xb4}\x07|\x01|\x07\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x06|\x07\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00k\x03\x00\x00\x00\x00\x90\x01r\x9d\t\x00|\x07|\x03v\x00\x90\x01r\x9ct\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x03|\x07\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x03|\x07d\x03z\n\x00\x00\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00|\x07d\x04z\n\x00\x00|\x07d\x05z\x00\x00\x00\x85\x02\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04|\x07d\x04z\n\x00\x00|\x07d\x05z\x00\x00\x00\x85\x02\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00n\x01\x8c\x8et#\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x06\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x82\x01d\x00S\x00d\x00S\x00'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/florian/tmp/lark/.tox/py311/lib/python3.11/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/lark/.tox/py311/lib/python3.11/site-packages/js2py/base.py", line 6, in <module>
    from .utils.injector import fix_js_args
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/lark/.tox/py311/lib/python3.11/site-packages/js2py/utils/injector.py", line 224, in <module>
    check(six.get_function_code(check))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/lark/.tox/py311/lib/python3.11/site-packages/js2py/utils/injector.py", line 220, in check
    raise RuntimeError(
    ^^^^^^^^^^^^^^^^^^^
RuntimeError: Your python version made changes to the bytecode
```

**Comment by idkman2021** [comment]
what does this mean cuz I have the same issue but with a different package

**Comment by idkman2021** [comment]
"Your python version made changes to the bytecode" what in the world could that even mean

**Comment by PiotrDabkowski** [comment]
Yeah, it seems Python 3.11 modified the bytecode specification, and the bytecode manipulations done by Js2Py do not work in that version. Given that 3.11 will become more used now it is quite important to fix this issue.

I am bit busy now with my startup so any contributions welcome! Otherwise I will try to fix that later on when I find some time.

**Comment by devenu85** [comment]
please fix this asap.

**Comment by 4144** [comment]
In 3.12.0a2+ (current main branch) fail in injector.py too

**Comment by PiotrDabkowski** [comment]
Ehh why do they change bytecode so frequently now? It was stabole for years... Adjusting it after bytecode change is relatively hard because I need to reverse engineer it due to poor documentation.
If anybody wants to play with 3.12, contributions very welcome!

**Comment by ylm-king** [comment]
good lib, and wait python3.12 support +1

**Comment by servicecomp54** [comment]
Not work on Python 3.13. Can anyone help?

>pipwin install pycuda

b"\x95\x00U\x00R\x00n\x01[\x03[\x05U\x005\x015\x01n\x020\x00n\x03/\x00n\x04U\x02\x13\x00H?n\x05XS[\x07U\x045\x01'\x00U\x04R\t[\x0bU\x05R\x0cU\x05R\x0e5\x025\x01 \x00MA\x0b\x00 \x00[\x10R\x12(\x00a\x12S\x01R\x15U\x045\x01n\x06O\x0b[\x17U\x045\x01n\x06Xa:wa\xbc[\x19U\x065\x01 \x00[\x19U\x015\x01 \x00[\x1b[\x1d[\x07U\x065\x01[\x07U\x015\x015\x025\x01\x13\x00Hzn\x07X\x17\x05\x00Xg\x05\x00:wad\x1e\x00Xs;\x00a\\[\x19X7\x05\x005\x01 \x00[\x19X7S\x02-\n\x05\x005\x01 \x00[\x19[\x03[\x1f[ U\x015\x025\x01U\x07S\x03-\nU\x07S\x04-\x00\x04\x005\x01 \x00[\x19XGS\x03-\nU\x07S\x04-\x00\x04\x005\x01 \x00O\x02Mc[#S\x055\x01e\x01\x0b\x00 \x00g\x00g\x00"
b"\x95\x00U\x00R\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00n\x01[\x03\x00\x00\x00\x00\x00\x00\x00\x00[\x05\x00\x00\x00\x00\x00\x00\x00\x00U\x005\x01\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00n\x020\x00n\x03/\x00n\x04U\x02\x13\x00H?\x00\x00n\x05XS[\x07\x00\x00\x00\x00\x00\x00\x00\x00U\x045\x01\x00\x00\x00\x00\x00\x00'\x00\x00\x00U\x04R\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[\x0b\x00\x00\x00\x00\x00\x00\x00\x00U\x05R\x0c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00U\x05R\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x005\x02\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00 \x00MA\x00\x00\x0b\x00 \x00[\x10\x00\x00\x00\x00\x00\x00\x00\x00R\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00(\x00\x00\x00\x00\x00\x00\x00a\x12\x00\x00S\x01R\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00U\x045\x01\x00\x00\x00\x00\x00\x00n\x06O\x0b[\x17\x00\x00\x00\x00\x00\x00\x00\x00U\x045\x01\x00\x00\x00\x00\x00\x00n\x06Xa:w\x00\x00a\xbc\x00\x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00U\x065\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00U\x015\x01\x00\x00\x00\x00\x00\x00 \x00[\x1b\x00\x00\x00\x00\x00\x00\x00\x00[\x1d\x00\x00\x00\x00\x00\x00\x00\x00[\x07\x00\x00\x00\x00\x00\x00\x00\x00U\x065\x01\x00\x00\x00\x00\x00\x00[\x07\x00\x00\x00\x00\x00\x00\x00\x00U\x015\x01\x00\x00\x00\x00\x00\x005\x02\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00\x13\x00Hz\x00\x00n\x07X\x17\x05\x00\x00\x00Xg\x05\x00\x00\x00:w\x00\x00ad\x00\x00\x1e\x00Xs;\x00\x00\x00a\\\x00\x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00X7\x05\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00X7S\x02-\n\x00\x00\x05\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00[\x03\x00\x00\x00\x00\x00\x00\x00\x00[\x1f\x00\x00\x00\x00\x00\x00\x00\x00[ \x00\x00\x00\x00\x00\x00\x00\x00U\x015\x02\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00U\x07S\x03-\n\x00\x00U\x07S\x04-\x00\x00\x00\x04\x005\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00XGS\x03-\n\x00\x00U\x07S\x04-\x00\x00\x00\x04\x005\x01\x00\x00\x00\x00\x00\x00 \x00O\x02Mc\x00\x00[#\x00\x00\x00\x00\x00\x00\x00\x00S\x055\x01\x00\x00\x00\x00\x00\x00e\x01\x0b\x00 \x00g\x00g\x00"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python313\Scripts\pipwin.exe\__main__.py", line 4, in <module>
    from pipwin.command import main
  File "C:\Python313\Lib\site-packages\pipwin\command.py", line 28, in <module>
    from . import pipwin, __version__
  File "C:\Python313\Lib\site-packages\pipwin\pipwin.py", line 13, in <module>
    import js2py
  File "C:\Python313\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Python313\Lib\site-packages\js2py\base.py", line 6, in <module>
    from .utils.injector import fix_js_args
  File "C:\Python313\Lib\site-packages\js2py\utils\injector.py", line 264, in <module>
    check(six.get_function_code(check))
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\js2py\utils\injector.py", line 251, in check
    raise RuntimeError(
        'Your python version made changes to the bytecode')
RuntimeError: Your python version made changes to the bytecode

**Comment by Zerogoki00** [comment]
same problem what is the solution?

**Comment by Anime-pdf** [comment]
3.14 same problem

```
C:\Users\Paul>pipwin install PyAudio
b"\x80\x00V\x00P\x00p\x01\\\x03\\\x05V\x004\x014\x01p\x02/\x00p\x03.\x00p\x04V\x02\x10\x00F?p\x05WS\\\x07V\x044\x01&\x00V\x04P\t\\\x0bV\x05P\x0cV\x05P\x0e4\x024\x01\x1f\x00KA\t\x00\x1e\x00\\\x10P\x12'\x00d\x13\x1c\x00R\x00P\x15V\x044\x01p\x06M\x0b\\\x17V\x044\x01p\x06Wa8wd\xe4\x1c\x00\\\x19V\x064\x01\x1f\x00\\\x19V\x014\x01\x1f\x00\\\x1b\\\x1d\\\x07V\x064\x01\\\x07V\x014\x014\x024\x01\x10\x00F\xa0p\x07W\x17,\x1aWg,\x1a8wd\x82\x1c\x00\x1b\x00Ws9\x00g\x03\x1c\x00K\t\\\x19W7,\x1a4\x01\x1f\x00\\\x19W7^\x02,\n,\x1a4\x01\x1f\x00\\\x19\\\x03\\\x1f\\ V\x014\x024\x01V\x07^\x04,\nV\x07^\x08,\x00\x01\x004\x01\x1f\x00\\\x19WG^\x04,\nV\x07^\x08,\x00\x01\x004\x01\x1f\x00\x1b\x00\\#R\x014\x01h\x01\t\x00\x1e\x00R\x02#\x00R\x02#\x00"
b"\x80\x00V\x00P\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00p\x01\\\x03\x00\x00\x00\x00\x00\x00\x00\x00\\\x05\x00\x00\x00\x00\x00\x00\x00\x00V\x004\x01\x00\x00\x00\x00\x00\x004\x01\x00\x00\x00\x00\x00\x00p\x02/\x00p\x03.\x00p\x04V\x02\x10\x00F?\x00\x00p\x05WS\\\x07\x00\x00\x00\x00\x00\x00\x00\x00V\x044\x01\x00\x00\x00\x00\x00\x00&\x00\x00\x00V\x04P\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\\\x0b\x00\x00\x00\x00\x00\x00\x00\x00V\x05P\x0c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00V\x05P\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004\x02\x00\x00\x00\x00\x00\x004\x01\x00\x00\x00\x00\x00\x00\x1f\x00KA\x00\x00\t\x00\x1e\x00\\\x10\x00\x00\x00\x00\x00\x00\x00\x00P\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'\x00\x00\x00\x00\x00\x00\x00d\x13\x00\x00\x1c\x00R\x00P\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00V\x044\x01\x00\x00\x00\x00\x00\x00p\x06M\x0b\\\x17\x00\x00\x00\x00\x00\x00\x00\x00V\x044\x01\x00\x00\x00\x00\x00\x00p\x06Wa8w\x00\x00d\xe4\x00\x00\x1c\x00\\\x19\x00\x00\x00\x00\x00\x00\x00\x00V\x064\x01\x00\x00\x00\x00\x00\x00\x1f\x00\\\x19\x00\x00\x00\x00\x00\x00\x00\x00V\x014\x01\x00\x00\x00\x00\x00\x00\x1f\x00\\\x1b\x00\x00\x00\x00\x00\x00\x00\x00\\\x1d\x00\x00\x00\x00\x00\x00\x00\x00\\\x07\x00\x00\x00\x00\x00\x00\x00\x00V\x064\x01\x00\x00\x00\x00\x00\x00\\\x07\x00\x00\x00\x00\x00\x00\x00\x00V\x014\x01\x00\x00\x00\x00\x00\x004\x02\x00\x00\x00\x00\x00\x004\x01\x00\x00\x00\x00\x00\x00\x10\x00F\xa0\x00\x00p\x07W\x17,\x1a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Wg,\x1a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x008w\x00\x00d\x82\x00\x00\x1c\x00\x1b\x00Ws9\x00\x00\x00g\x03\x00\x00\x1c\x00K\t\x00\x00\\\x19\x00\x00\x00\x00\x00\x00\x00\x00W7,\x1a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004\x01\x00\x00\x00\x00\x00\x00\x1f\x00\\\x19\x00\x00\x00\x00\x00\x00\x00\x00W7^\x02,\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,\x1a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004\x01\x00\x00\x00\x00\x00\x00\x1f\x00\\\x19\x00\x00\x00\x00\x00\x00\x00\x00\\\x03\x00\x00\x00\x00\x00\x00\x00\x00\\\x1f\x00\x00\x00\x00\x00\x00\x00\x00\\ \x00\x00\x00\x00\x00\x00\x00\x00V\x014\x02\x00\x00\x00\x00\x00\x004\x01\x00\x00\x00\x00\x00\x00V\x07^\x04,\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00V\x07^\x08,\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x004\x01\x00\x00\x00\x00\x00\x00\x1f\x00\\\x19\x00\x00\x00\x00\x00\x00\x00\x00WG^\x04,\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00V\x07^\x08,\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x004\x01\x00\x00\x00\x00\x00\x00\x1f\x00\x1b\x00\\#\x00\x00\x00\x00\x00\x00\x00\x00R\x014\x01\x00\x00\x00\x00\x00\x00h\x01\t\x00\x1e\x00R\x02#\x00R\x02#\x00"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Paul\AppData\Roaming\Python\Python314\Scripts\pipwin.exe\__main__.py", line 2, in <module>
    from pipwin.command import main
  File "C:\Users\Paul\AppData\Roaming\Python\Python314\site-packages\pipwin\command.py", line 28, in <module>
    from . import pipwin, __version__
  File "C:\Users\Paul\AppData\Roaming\Python\Python314\site-packages\pipwin\pipwin.py", line 13, in <module>
    import js2py
  File "C:\Users\Paul\AppData\Roaming\Python\Python314\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\Paul\AppData\Roaming\Python\Python314\site-packages\js2py\base.py", line 6, in <module>
    from .utils.injector import fix_js_args
  File "C:\Users\Paul\AppData\Roaming\Python\Python314\site-packages\js2py\utils\injector.py", line 264, in <module>
    check(six.get_function_code(check))
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paul\AppData\Roaming\Python\Python314\site-packages\js2py\utils\injector.py", line 251, in check
    raise RuntimeError(
        'Your python version made changes to the bytecode')
RuntimeError: Your python version made changes to the bytecode
```
