### ISSUE TITLE
AssertionError: Could not link required node_modules

### ISSUE THREAD

**Issue by Jack-samu** [PiotrDabkowski/Js2Py#285]
When I use the module to exchange the js library, it return this to me.
`>>> import js2py
>>> encrypt = js2py.require('jsencrypt.min.js')
v16.15.0
文件名、目录名或卷标语法不正确。
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\应用安装\Python38-32\lib\site-packages\js2py\node_import.py", line 155, in require
    py_code = _get_and_translate_npm_module(module_name, include_polyfill=include_polyfill, update=update,
  File "D:\应用安装\Python38-32\lib\site-packages\js2py\node_import.py", line 77, in _get_and_translate_npm_module
    _init()
  File "D:\应用安装\Python38-32\lib\site-packages\js2py\node_import.py", line 23, in _init
    assert subprocess.call(
AssertionError: Could not link required node_modules
>>>`

**Comment by lol-idk-hehe** [comment]
https://lightrun.com/answers/piotrdabkowski-js2py-js2pyrequirepaper--assertionerror-could-not-link-required-node_modules this might help
