### ISSUE TITLE
unable to import js2py

### ISSUE THREAD

**Issue by adilyacoubi** [PiotrDabkowski/Js2Py#30]
installed with PIP . Python 2.6
All packages are installed automatically
Error : 

>>> import js2py

Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    import js2py
  File "C:\Python26\lib\site-packages\js2py\__init__.py", line 67, in <module>
    from .evaljs import *
  File "C:\Python26\lib\site-packages\js2py\evaljs.py", line 4, in <module>
    from .translators import translate_js, DEFAULT_HEADER
  File "C:\Python26\lib\site-packages\js2py\translators\__init__.py", line 25, in <module>
    from .pyjsparser import PyJsParser, Node, WrappingNode, node_to_dict
  File "C:\Python26\lib\site-packages\js2py\translators\pyjsparser.py", line 25
    REGEXP_SPECIAL_SINGLE = {'\\', '^', '$', '*', '+', '?', '.', '[', ']', '(', ')', '{', '{', '|'}
                                 ^
SyntaxError: invalid syntax

**Comment by PiotrDabkowski** [comment]
Python 2.6 may not be supported. Please try with Python 2.7 or 3.X

**Comment by adilyacoubi** [comment]
Ok.
Thank you for your answer.
