### ISSUE TITLE
Numpy required for Js2Py?

### ISSUE THREAD

**Issue by MikeUdin** [PiotrDabkowski/Js2Py#300]
Hello! During first launch the module returns this error code with traceback:
`Traceback (most recent call last):
  File "/Users/mikeudin/Library/CloudStorage/GoogleDrive-bondura2@gmail.com/My Drive/Developer/Plugins/vTexter/tests/test_js2py.py", line 46, in <module>
    main()
  File "/Users/mikeudin/Library/CloudStorage/GoogleDrive-bondura2@gmail.com/My Drive/Developer/Plugins/vTexter/tests/test_js2py.py", line 41, in main
    context.execute(SCRIPT)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/evaljs.py", line 199, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/evaljs.py", line 162, in _js_require_impl
    return require(to_python(npm_module_name), context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/node_import.py", line 166, in require
    exec(py_code, context)
  File "<string>", line 32269, in <module>
  File "<string>", line 32268, in PyJs_LONG_2046_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32259, in PyJsHoisted_r_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32250, in PyJsHoisted_o_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 996, in callprop
    return cand.call(self, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/prototypes/jsfunction.py", line 27, in call
    return this.call(obj, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 231, in PyJs_anonymous_7_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32248, in PyJs_anonymous_2045_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32250, in PyJsHoisted_o_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 996, in callprop
    return cand.call(self, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/prototypes/jsfunction.py", line 27, in call
    return this.call(obj, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 317, in PyJs_anonymous_12_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 996, in callprop
    return cand.call(self, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/prototypes/jsfunction.py", line 27, in call
    return this.call(obj, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 315, in PyJs_anonymous_13_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 996, in callprop
    return cand.call(self, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/prototypes/jsfunction.py", line 27, in call
    return this.call(obj, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 296, in PyJs_anonymous_14_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32248, in PyJs_anonymous_2045_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32250, in PyJsHoisted_o_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 996, in callprop
    return cand.call(self, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/prototypes/jsfunction.py", line 27, in call
    return this.call(obj, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 14492, in PyJs_anonymous_1135_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32248, in PyJs_anonymous_2045_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32250, in PyJsHoisted_o_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 996, in callprop
    return cand.call(self, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/prototypes/jsfunction.py", line 27, in call
    return this.call(obj, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 12868, in PyJs_anonymous_969_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32248, in PyJs_anonymous_2045_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 32250, in PyJsHoisted_o_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 996, in callprop
    return cand.call(self, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/prototypes/jsfunction.py", line 27, in call
    return this.call(obj, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 7945, in PyJs_anonymous_488_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 5401, in PyJs_anonymous_242_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "<string>", line 7943, in PyJs_anonymous_490_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1464, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/constructors/jsuint16array.py", line 32, in Uint16Array
    temp = Js(numpy.array(array, dtype=numpy.uint16))
NameError: name 'numpy' is not defined`

**Comment by worstperson** [comment]
It's an optional dependency for TypedArray support. Only required if your code needs it.
