### ISSUE TITLE
KeyError: 3 while importing js2py

### ISSUE THREAD

**Issue by CS8867** [PiotrDabkowski/Js2Py#324]
The error occurs below as follows -
Traceback (most recent call last):
  File "C:\Users\chsubhed\Documents\Work\Tests\Python\test.py", line 1, in <module>
    import time, js2py
  File "C:\Users\chsubhed\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\chsubhed\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\chsubhed\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chsubhed\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\chsubhed\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args      
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chsubhed\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

python version = 3.12.0
pip version = 24.0

**Comment by 4144** [comment]
python 3.12 not supported yet.
See #282

**Comment by josdejong** [comment]
Any news on this?

**Comment by tonal** [comment]
see #317

**Comment by hetang-crest** [comment]
Any update on the fix or is the library not compatible with Py 3.12?
