### ISSUE TITLE
Title: KeyError: 3 in `append_arguments` function of `utils/injector.py`

### ISSUE THREAD

**Issue by Foadsf** [PiotrDabkowski/Js2Py#329]
**Description:**

I encountered a `KeyError` while trying to use `pipwin` to install the `pyppf` package. The error seems to originate from the `js2py` package, specifically in the `append_arguments` function of the `utils/injector.py` module.

**Traceback:**

```plaintext
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\Scripts\pipwin.exe\__main__.py", line 4, in <module>
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\pipwin\command.py", line 28, in <module>
    from . import pipwin, __version__
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\pipwin\pipwin.py", line 13, in <module>
    import js2py
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foobar\AppData\Roaming\Python\Python312\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
```

**Steps to Reproduce:**

1. Install `pipwin` using `pip install pipwin`.
2. Run `pipwin install pyppf`.

**Environment:**

- Operating System: Windows 10
- Python Version: 3.12
- `js2py` Version: 0.71 (latest as of the issue date)
- `pipwin` Version: Latest available

**Additional Information:**

The error occurs because the `name_translations` dictionary does not contain the key `3`. This leads to a `KeyError` in the `append_arguments` function of the `utils/injector.py` module. 

**Potential Fix:**

A possible fix would be to handle the missing key scenario in the `append_arguments` function. For instance:

```python
def append_arguments(code, names):
    # existing code ...
    try:
        arg = name_translations[inst.arg]
    except KeyError:
        continue  # or handle the missing key appropriately
    # remaining code ...
```

I hope this information helps in resolving the issue. Thank you for your assistance!

**Comment by HeinrichWizardKreuser** [comment]
Getting this as well, simply when importing js2py.

```
❯ ipython3
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.25.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import js2py
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 1
----> 1 import js2py

File /usr/local/Cellar/ipython/8.25.0/libexec/lib/python3.12/site-packages/js2py/__init__.py:72
     64 __author__ = 'Piotr Dabkowski'
     65 __all__ = [
     66     'EvalJs', 'translate_js', 'import_js', 'eval_js', 'parse_js',
     67     'translate_file', 'run_file', 'disable_pyimport', 'eval_js6',
     68     'translate_js6', 'PyJsException', 'get_file_contents',
     69     'write_file_contents', 'require'
     70 ]
---> 72 from .base import PyJsException
     73 from .evaljs import *
     74 from .translators import parse as parse_js

File /usr/local/Cellar/ipython/8.25.0/libexec/lib/python3.12/site-packages/js2py/base.py:2965
   2959             self.own['message']['enumerable'] = False
   2962 ErrorPrototype = PyJsError(Js(''), ObjectPrototype)
-> 2965 @Js
   2966 def Error(message):
   2967     return PyJsError(None if message.is_undefined() else message,
   2968                      ErrorPrototype)
   2971 Error.create = Error

File /usr/local/Cellar/ipython/8.25.0/libexec/lib/python3.12/site-packages/js2py/base.py:165, in Js(val, Clamped)
    163     return PyJsNumber(float(val), NumberPrototype)
    164 elif isinstance(val, FunctionType):
--> 165     return PyJsFunction(val, FunctionPrototype)
    166 #elif isinstance(val, ModuleType):
    167 #    mod = {}
    168 #    for name in dir(val):
   (...)
    178 #    return Js(mod)
    179 #elif isintance(val, ClassType):
    181 elif isinstance(val, dict):  # convert to object

File /usr/local/Cellar/ipython/8.25.0/libexec/lib/python3.12/site-packages/js2py/base.py:1377, in PyJsFunction.__init__(self, func, prototype, extensible, source)
   1376 def __init__(self, func, prototype=None, extensible=True, source=None):
-> 1377     cand = fix_js_args(func)
   1378     has_scope = cand is func
   1379     func = cand

File /usr/local/Cellar/ipython/8.25.0/libexec/lib/python3.12/site-packages/js2py/utils/injector.py:27, in fix_js_args(func)
     25 if fargs == ('this', 'arguments') or fargs == ('arguments', 'var'):
     26     return func
---> 27 code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
     29 result = types.FunctionType(
     30     code,
     31     six.get_function_globals(func),
     32     func.__name__,
     33     closure=six.get_function_closure(func))
     34 return result

File /usr/local/Cellar/ipython/8.25.0/libexec/lib/python3.12/site-packages/js2py/utils/injector.py:121, in append_arguments(code_obj, new_locals)
    118     arg = varname_translations[inst.arg]
    119 elif inst.opcode in opcode.hasname:
    120     # for example STORE_GLOBAL
--> 121     arg = name_translations[inst.arg]
    122 elif is_new_bytecode and inst.opcode in opcode.hasfree:
    123     # Python 3.11+ adds refs at the end (after locals), for whatever reason...
    124     if inst.argval not in code_obj.co_varnames[:code_obj.co_argcount]:  # we do not need to remap existing arguments, they are not shifted by new ones.
```

**Steps to Reproduce:**
1. import js2py

**Environment**:
- Operating System: macOS 14.4.1
- Python Version: 3.12.4
- `js2py` Version: 0.74 (latest as of the issue date)

**Comment by LJC8888888888** [comment]
\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
KeyError: 3
Steps to Reproduce:

import js2py
Environment:

Operating System: win11
Python Version: 3.12.4
js2py Version: 0.74 (latest as of the issue date)

**Comment by lorenmh** [comment]
I saw the same issue using 3.12 as @HeinrichWizardKreuser, I downgraded to 3.10 and importing `js2py` seems to work

**Comment by staciax** [comment]
<img width="1231" alt="Screenshot 2567-07-19 at 18 04 13" src="https://github.com/user-attachments/assets/52a7b5d3-9f05-4461-961d-5fb425269228">

Python Version: 3.12
OS: MacOS 14.5
Version: 0.74

**Comment by staciax** [comment]
```py
import js2py

js2py.eval_js('console.log( "Hello World!" )')
```

```py
Traceback (most recent call last):
  File "/Users/[user]/Documents/GitHub/test/test.py", line 1, in <module>
    import js2py
  File "/Users/[user]/Documents/GitHub/test/.venv/lib/python3.12/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/Users/[user]/Documents/GitHub/test/.venv/lib/python3.12/site-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/Users/[user]/Documents/GitHub/test/.venv/lib/python3.12/site-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[user]/Documents/GitHub/test/.venv/lib/python3.12/site-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/Users/[user]/Documents/GitHub/test/.venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[user]/Documents/GitHub/test/.venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
```

Python Version: 3.12
OS: MacOS 14.5
Version: 0.74

**Comment by jonejkim** [comment]
Hello, just pitching in my observation. Not sure if it will be a hint.

I was getting the same manifestation error (e.g. KeyError: 3 on the same line) but in my case this error was surfacing while working in venv, whereas with the system installed it did not raise this error. My venv python interpreter is 3.12.5 (also got same error with 3.11) and system is 3.12.4 (installed w/ distro package manager). This was the case for me while working on Manjaro Linux.

I was wondering if having js2py installed in venv could possibly cause issues in reaching the system install nodejs? I may be wrong but hope if it may be a hint.

**Comment by 4144** [comment]
this error related to new python version.
need use non merged fix for py2js or use older python.

Here is fix https://github.com/PiotrDabkowski/Js2Py/pull/327

**Comment by hellcatmon** [comment]
> this error related to new python version. need use non merged fix for py2js or use older python.
> 
> Here is fix #327

Thanks for the fix, works fine for me

**Comment by hellcatmon** [comment]
Hey @PiotrDabkowski could you please merge this to restore the functionality of the library and its dependent libraries? I've faced with the ozon3 library has a similar issue. Thanks
