### ISSUE TITLE
[Bug] Python3.13 RuntimeError: Your python version made changes to the bytecode

### ISSUE THREAD

**Issue by leeskyler-top** [PiotrDabkowski/Js2Py#334]
"C:\Program Files\Python313\python.exe" D:\Python\web-scraper\test\CasService\DES.py 
Traceback (most recent call last):
  File "D:\Python\web-scraper\test\CasService\DES.py", line 1, in <module>
    from js2py.pyjs import *
  File "C:\Users\Skyler\AppData\Roaming\Python\Python313\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\Skyler\AppData\Roaming\Python\Python313\site-packages\js2py\base.py", line 6, in <module>
    from .utils.injector import fix_js_args
  File "C:\Users\Skyler\AppData\Roaming\Python\Python313\site-packages\js2py\utils\injector.py", line 264, in <module>
    check(six.get_function_code(check))
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Skyler\AppData\Roaming\Python\Python313\site-packages\js2py\utils\injector.py", line 251, in check
    raise RuntimeError(
        'Your python version made changes to the bytecode')
RuntimeError: Your python version made changes to the bytecode
b"\x95\x00U\x00R\x00n\x01[\x03[\x05U\x005\x015\x01n\x020\x00n\x03/\x00n\x04U\x02\x13\x00H?n\x05XS[\x07U\x045\x01'\x00U\x04R\t[\x0bU\x05R\x0cU\x05R\x0e5\x025\x01 \x00MA\x0b\x00 \x00[\x10R\x12(\x00a\x12S\x01R\x15U\x045\x01n\x06O\x0b[\x17U\x045\x01n\x06Xa:wa\xbc[\x19U\x065\x01 \x00[\x19U\x015\x01 \x00[\x1b[\x1d[\x07U\x065\x01[\x07U\x015\x015\x025\x01\x13\x00Hzn\x07X\x17\x05\x00Xg\x05\x00:wad\x1e\x00Xs;\x00a\\[\x19X7\x05\x005\x01 \x00[\x19X7S\x02-\n\x05\x005\x01 \x00[\x19[\x03[\x1f[ U\x015\x025\x01U\x07S\x03-\nU\x07S\x04-\x00\x04\x005\x01 \x00[\x19XGS\x03-\nU\x07S\x04-\x00\x04\x005\x01 \x00O\x02Mc[#S\x055\x01e\x01\x0b\x00 \x00g\x00g\x00"
b"\x95\x00U\x00R\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00n\x01[\x03\x00\x00\x00\x00\x00\x00\x00\x00[\x05\x00\x00\x00\x00\x00\x00\x00\x00U\x005\x01\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00n\x020\x00n\x03/\x00n\x04U\x02\x13\x00H?\x00\x00n\x05XS[\x07\x00\x00\x00\x00\x00\x00\x00\x00U\x045\x01\x00\x00\x00\x00\x00\x00'\x00\x00\x00U\x04R\t\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[\x0b\x00\x00\x00\x00\x00\x00\x00\x00U\x05R\x0c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00U\x05R\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x005\x02\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00 \x00MA\x00\x00\x0b\x00 \x00[\x10\x00\x00\x00\x00\x00\x00\x00\x00R\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00(\x00\x00\x00\x00\x00\x00\x00a\x12\x00\x00S\x01R\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00U\x045\x01\x00\x00\x00\x00\x00\x00n\x06O\x0b[\x17\x00\x00\x00\x00\x00\x00\x00\x00U\x045\x01\x00\x00\x00\x00\x00\x00n\x06Xa:w\x00\x00a\xbc\x00\x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00U\x065\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00U\x015\x01\x00\x00\x00\x00\x00\x00 \x00[\x1b\x00\x00\x00\x00\x00\x00\x00\x00[\x1d\x00\x00\x00\x00\x00\x00\x00\x00[\x07\x00\x00\x00\x00\x00\x00\x00\x00U\x065\x01\x00\x00\x00\x00\x00\x00[\x07\x00\x00\x00\x00\x00\x00\x00\x00U\x015\x01\x00\x00\x00\x00\x00\x005\x02\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00\x13\x00Hz\x00\x00n\x07X\x17\x05\x00\x00\x00Xg\x05\x00\x00\x00:w\x00\x00ad\x00\x00\x1e\x00Xs;\x00\x00\x00a\\\x00\x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00X7\x05\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00X7S\x02-\n\x00\x00\x05\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00[\x03\x00\x00\x00\x00\x00\x00\x00\x00[\x1f\x00\x00\x00\x00\x00\x00\x00\x00[ \x00\x00\x00\x00\x00\x00\x00\x00U\x015\x02\x00\x00\x00\x00\x00\x005\x01\x00\x00\x00\x00\x00\x00U\x07S\x03-\n\x00\x00U\x07S\x04-\x00\x00\x00\x04\x005\x01\x00\x00\x00\x00\x00\x00 \x00[\x19\x00\x00\x00\x00\x00\x00\x00\x00XGS\x03-\n\x00\x00U\x07S\x04-\x00\x00\x00\x04\x005\x01\x00\x00\x00\x00\x00\x00 \x00O\x02Mc\x00\x00[#\x00\x00\x00\x00\x00\x00\x00\x00S\x055\x01\x00\x00\x00\x00\x00\x00e\x01\x0b\x00 \x00g\x00g\x00"

**Comment by xiota** [comment]
Fork at [a-j-albert/Js2Py](https://github.com/a-j-albert/Js2Py) (@a-j-albert) contains some [commits](https://github.com/a-j-albert/Js2Py/compare/0da30c83f149b15539ca3d246d5ebfb0afd7f140~1..cc64a715727f110b79310b8031e0ade9c501d5d3) that address this issue.

**Comment by yesudeep** [comment]
This is blocking some of our development. Could the fork be examined for a review?

**Comment by Enase** [comment]
would be great to have it resolved. thanks in advance

**Comment by Zerogoki00** [comment]
same problem, how to fix?
