### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by cslatt05** [PiotrDabkowski/Js2Py#41]
>>> import js2py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/Js2Py-0.35-py2.6.egg/js2py/__init__.py", line 67, in <module>
    from .evaljs import *
  File "/usr/lib/python2.6/site-packages/Js2Py-0.35-py2.6.egg/js2py/evaljs.py", line 4, in <module>
    from .translators import translate_js, DEFAULT_HEADER
  File "/usr/lib/python2.6/site-packages/Js2Py-0.35-py2.6.egg/js2py/translators/__init__.py", line 25, in <module>
    from .pyjsparser import PyJsParser, Node, WrappingNode, node_to_dict
  File "/usr/lib/python2.6/site-packages/Js2Py-0.35-py2.6.egg/js2py/translators/pyjsparser.py", line 25
    REGEXP_SPECIAL_SINGLE = {'^', '$', '*', '+', '?', '.', '[', ']', '(', ')', '{', '{', '|', '-'}
                                ^
SyntaxError: invalid syntax

**Comment by PiotrDabkowski** [comment]
Hey, I think thats because of your python version. Only 2.7 or 3.X are supported
