### ISSUE TITLE
KeyError: 0.9722222222222222

### ISSUE THREAD

**Issue by civalin** [PiotrDabkowski/Js2Py#48]
Hello, I got a error when I run the following script:

```python3
import js2py

js = r'''
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('M l={"m":3,"n":"i","j":"3.0","k":r,"s":t,"o":"6","p":["q.0","9.0","8.0","7.0","f.0","g.0","h.0","e.0","b.0","c.0","d.0","a.0","u.0","L.0","D.0","K.0","I.0","J.0","N.0","R.0","S.0","O(1).0","P.0","Q.0","%2%5%4%2%5%4%H%y%A.0"],"x":v,"w":B,"F":"/G/z/E/6/","C":1}||{};',55,55,'jpg||E8|20275|8C|90|第04回|0003|0002|0001|0011|0008|0009|0010|0007|0004|0005|0006|终末的后宫|bpic|burl|cInfo|bid|bname|cname|files|0000|null|cid|241532|0012|false|len|finished|93||92|25|status|0014|zhongmodehougong_link|path|ps1|E5|0016|0017|0015|0013|var|0018|0021v2|0022|0023|0019|0020'.split('|'),0,{}))
'''

context = js2py.EvalJs()
context.execute(js)  # ERROR
context.eval('cInfo')
```

If success, this js script will write a global variable `cInfo` in javascript context. but i got ...

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/js2py/evaljs.py", line 131, in execute
    exec(compiled, self._context)
  File "<EvalJS snippet>", line 40, in <module>
  File "<EvalJS snippet>", line 39, in PyJs_LONG_5_
  File "/usr/local/lib/python3.4/dist-packages/js2py/base.py", line 835, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python3.4/dist-packages/js2py/base.py", line 1275, in call
    return Js(self.code(*args))
  File "<EvalJS snippet>", line 17, in PyJs_anonymous_1_
  File "/usr/local/lib/python3.4/dist-packages/js2py/base.py", line 835, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python3.4/dist-packages/js2py/base.py", line 1275, in call
    return Js(self.code(*args))
  File "<EvalJS snippet>", line 12, in PyJs_anonymous_2_
  File "/usr/local/lib/python3.4/dist-packages/js2py/base.py", line 875, in callprop
    return cand.call(self, args)
  File "/usr/local/lib/python3.4/dist-packages/js2py/base.py", line 1275, in call
    return Js(self.code(*args))
  File "/usr/local/lib/python3.4/dist-packages/js2py/prototypes/jsnumber.py", line 45, in toString
    s = RADIX_SYMBOLS[num % r]
KeyError: 0.9722222222222222
```

The Key not a integer or str... Maybe cause by `str` <-> `int` <-> `float` converting? But not really sure.

I also run this js code in node.js to make sure it is a valid script:

```javascript
user@mycompute ~/test/execjs $ nodejs
> eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[> eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('M l={"m":3,"n":"i","j":"3.0","k":r,"s":t,"o":"6","p":["q.0","9.0","8.0","7.0","f.0","g.0","h.0","e.0","b.0","c.0","d.0","a.0","u.0","L.0","D.0","K.0","I.0","J.0","N.0","R.0","S.0","O(1).0","P.0","Q.0","%2%5%4%2%5%4%H%y%A.0"],"x":v,"w":B,"F":"/G/z/E/6/","C":1}||{};',55,55,'jpg||E8|20275|8C|90|第04回|0003|0002|0001|0011|0008|0009|0010|0007|0004|0005|0006|终末的后宫|bpic|burl|cInfo|bid|bname|cname|files|0000|null|cid|241532|0012|en|finished|93||92|25|status|0014|zhongmodehougong_link|path|ps1|E5|0016|0017|0015|0013|var|0018|0021v2|0022|0023|0019|0020'.split('|'),0,{}))
undefined
> cInfo
{ bid: 20275,
  bname: '终末的后宫',
  bpic: '20275.jpg',
  burl: null,
  cid: 241532,
  cname: '第04回',
  files: 
   [ '0000.jpg',
     '0001.jpg',
     '0002.jpg',
     '0003.jpg',
     '0004.jpg',
     '0005.jpg',
     '0006.jpg',
     '0007.jpg',
     '0008.jpg',
     '0009.jpg',
     '0010.jpg',
     '0011.jpg',
     '0012.jpg',
     '0013.jpg',
     '0014.jpg',
     '0015.jpg',
     '0016.jpg',
     '0017.jpg',
     '0018.jpg',
     '0019.jpg',
     '0020.jpg',
     '0021v2(1).jpg',
     '0022.jpg',
     '0023.jpg',
     '%E8%90%8C%E8%90%8C%E5%93%92.jpg' ],
  finished: false,
  len: 25,
  path: '/ps1/z/zhongmodehougong_link/第04回/',
  status: 1 }
> 
```

## System Info

- ubuntu 15.10
- python: 3.4.3
- Js2Py version: 0.36
- how to install js2py: `sudo -H pip3 install js2py`

Thank you so!

**Comment by PiotrDabkowski** [comment]
Hey, it works with Python 2.7. I will try to fix the issue with Python 3, sorry for inconvenience!

**Comment by PiotrDabkowski** [comment]
Okay, fixed. Just change line 46 in prototype/jsnumber.py to `num = num // r` or update using pip.

**Comment by civalin** [comment]
nice work! thanks!
