### ISSUE TITLE
Bitwise operators with negative numbers don't work

### ISSUE THREAD

**Issue by AmaanC** [PiotrDabkowski/Js2Py#5]
In Python

    >>> import js2py
    >>> js2py.eval_js('12 | -4')
    2147483644
    >>> 

In [JavaScript](http://jsconsole.com/?12%20%7C%20-4):

    > 12 | -4
    -4

Similarly, js2py fails to work with other bitwise operators too.

**Comment by AmaanC** [comment]
In the same vein, bitwise not just throws an error:

    >>> js2py.eval_js('~4')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/js2py/evaljs.py", line 40, in eval_js
        return e.eval(js)
      File "/usr/local/lib/python2.7/dist-packages/js2py/evaljs.py", line 67, in eval
        self.execute(code)
      File "/usr/local/lib/python2.7/dist-packages/js2py/evaljs.py", line 62, in execute
        exec code in self._context
      File "<string>", line 2, in <module>
      File "/usr/local/lib/python2.7/dist-packages/js2py/base.py", line 752, in __call__
        return self.call(self.GlobalObject, args) # todo  value of this
      File "/usr/local/lib/python2.7/dist-packages/js2py/base.py", line 1141, in call
        return Js(self.code(*args))
      File "/usr/local/lib/python2.7/dist-packages/js2py/host/jseval.py", line 40, in Eval
        executor(py_code)
      File "/usr/local/lib/python2.7/dist-packages/js2py/host/jseval.py", line 47, in executor
        exec code in globals()
      File "<string>", line 2, in <module>
    TypeError: bad operand type for unary ~: 'PyJsNumber'

**Comment by PiotrDabkowski** [comment]
Thank you for that. Fixed

**Comment by AmaanC** [comment]
Brilliant, thanks!
