### ISSUE TITLE
Brackets don't work as expected

### ISSUE THREAD

**Issue by wigvp** [PiotrDabkowski/Js2Py#54]
```
context = js2py.EvalJs()
context.execute("var a = (1);")
```

gives an error:

```
Traceback (most recent call last):
  File "/bin/user_wsgi_wrapper.py", line 154, in __call__
    app_iterator = self.app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/wrappers.py", line 827, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/test.py", line 855, in run_wsgi_app
    app_iter = app(environ, start_response)
  File "/home/PAuser/.local/lib/python3.4/site-packages/js2py/base.py", line 1056, in __call__
    return to_python(parent._obj.callprop(meth, *args))
  File "/home/PAuser/.local/lib/python3.4/site-packages/js2py/base.py", line 874, in callprop
    raise  MakeError('TypeError','%s is not a function'%cand.typeof())
js2py.base.PyJsException: TypeError: 'object' is not a function
```

**Comment by PiotrDabkowski** [comment]
No it does not. Try it :)

**Comment by PiotrDabkowski** [comment]
Make sure you are using latest Js2Py

**Comment by wigvp** [comment]
I just installed it...

**Comment by PiotrDabkowski** [comment]
Try `print(js2py.translate_js("var a = (1);")` and send me the result please.

**Comment by wigvp** [comment]
It's printing out nothing. It's just blocking...

**Comment by PiotrDabkowski** [comment]
Try again

**Comment by wigvp** [comment]
OK

**Comment by wigvp** [comment]
Again. It's just blocking. Like so: http://i.imgur.com/hDSEywp.png

**Comment by wigvp** [comment]
Oh, sorry

**Comment by wigvp** [comment]
I forgot one bracket

**Comment by wigvp** [comment]
```from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)
# Code follows:
var.registers(['a'])
var.put('a', Js(1.0))
pass```

**Comment by wigvp** [comment]
Seems like it should work...

**Comment by PiotrDabkowski** [comment]
Yep, try again to your example :)

**Comment by wigvp** [comment]
Wooaaaah, it's working! Great job! Thank you!

**Comment by PiotrDabkowski** [comment]
Haha I did a lot lol
