### ISSUE TITLE
NotImplementedError while calling Javascript function with date argument

### ISSUE THREAD

**Issue by darshit7** [PiotrDabkowski/Js2Py#58]
'function test(cronjob) { [python code] }'
later.data('* * 1 1 * */2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/base.py", line 1056, in __call__
    return to_python(parent._obj.callprop(meth, *args))
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/base.py", line 875, in callprop
    return cand.call(self, args)
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/base.py", line 1281, in call
    return Js(self.code(*args))
  File "later.py", line 2346, in PyJs_test_227_
    var.put(u'next_date', var.get(u'later').callprop(u'schedule', var.get(u'schedule')).callprop(u'next', Js(10.0), var.get(u'Date').create()))
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/base.py", line 875, in callprop
    return cand.call(self, args)
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/base.py", line 1281, in call
    return Js(self.code(*args))
  File "later.py", line 1346, in PyJs_anonymous_155_
    return var.get(u'getInstances')(Js(u'next'), (var.get(u'count') or Js(1.0)), var.get(u'startDate'), var.get(u'endDate'))
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/base.py", line 835, in __call__
    return self.call(self.GlobalObject, args)
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/base.py", line 1281, in call
    return Js(self.code(*args))
  File "later.py", line 1181, in PyJsHoisted_getInstances_
    var.put(u'startDate', (var.get(u'Date').create(var.get(u'startDate')) if var.get(u'startDate') else var.get(u'Date').create()))
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/constructors/jsdate.py", line 104, in date_constructor
    return date_constructor1(args[0])
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/constructors/jsdate.py", line 119, in date_constructor1
    return PyJsDate(TimeClip(v), prototype=DatePrototype)
  File "/home/darshitp/.local/lib/python2.7/site-packages/js2py/constructors/time_helpers.py", line 178, in TimeClip
    if t!=t or abs(t)==float('inf'):
TypeError: bad operand type for abs(): 'exceptions.NotImplementedError'

Javascript function is:
data = function test(exp){
    var schedule = later.parse.cron(exp);
    var next_date = later.schedule(schedule).next(10, new Date());
    return next_date
}

**Comment by PiotrDabkowski** [comment]
Parsing JS date strings was not implemented before, added partial support for it.
