### ISSUE TITLE
Error running basic example

### ISSUE THREAD

**Issue by andrebrussee** [PiotrDabkowski/Js2Py#59]
Hi Piotr, I installes OK however running example gives error

See dump, any suggestions ?

many thanks,

André
Python 3.6.0b1 (default, Sep 12 2016, 18:11:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import js2py
>>> js2py.eval_js('console.log( "Hello World!" )')
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    js2py.eval_js('console.log( "Hello World!" )')
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\evaljs.py", line 109, in eval_js
    e = EvalJs()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\evaljs.py", line 134, in __init__
    exec(DEFAULT_HEADER, self._context)
  File "<string>", line 1, in <module>
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\pyjs.py", line 1, in <module>
    from .base import *
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\base.py", line 1564, in <module>
    FunctionPrototype = PyJsFunction(Empty, ObjectPrototype)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\base.py", line 1216, in __init__
    cand = fix_js_args(func)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\utils\injector.py", line 23, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this','arguments'))
  File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\utils\injector.py", line 84, in append_arguments
    raise ValueError("a name was lost in translation")
ValueError: a name was lost in translation
>>>

**Comment by PiotrDabkowski** [comment]
Can you specify what example you tried to run?

**Comment by andrebrussee** [comment]
This one

 

import js2py
js2py.eval_js('console.log( "Hello World!" )')

 

error

 

Traceback (most recent call last):
File "", line 1, in 
js2py.eval_js('console.log( "Hello World!" )')
File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\evaljs.py", line 109, in eval_js
e = EvalJs()
File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\evaljs.py", line 134, in init
exec(DEFAULT_HEADER, self.context)
File "", line 1, in 
File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\pyjs.py", line 1, in 
from .base import *
File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\base.py", line 1564, in 
FunctionPrototype = PyJsFunction(Empty, ObjectPrototype)
File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\base.py", line 1216, in __init_
cand = fix_js_args(func)
File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\utils\injector.py", line 23, in fix_js_args
code = append_arguments(six.get_function_code(func), ('this','arguments'))
File "C:\Users\andre\AppData\Local\Programs\Python\Python36\lib\site-packages\js2py\utils\injector.py", line 84, in append_arguments
raise ValueError("a name was lost in translation")
ValueError: a name was lost in translation

Bovenkant formulier

Onderkant formulier

 <https://github.com/PiotrDabkowski> @PiotrDabkowski

 

Owner

 <https://github.com/PiotrDabkowski> PiotrDabkowski commented  <https://github.com/PiotrDabkowski/Js2Py/issues/59#issuecomment-248924807> 23 minutes ago

Can you specify what example you tried to run?

 <https://github.com/andrebrussee> @andrebrussee

Bovenkant formulier

 

 

 

 

 

Write Preview

Van: Piotr Dabkowski [mailto:notifications@github.com] 
Verzonden: donderdag 22 september 2016 16:45
Aan: PiotrDabkowski/Js2Py
CC: andrebrussee; Author
Onderwerp: Re: [PiotrDabkowski/Js2Py] Error running basic example (#59)

 

Can you specify what example you tried to run?

**Comment by PiotrDabkowski** [comment]
Probably this is because you are using new Python 3.6. Try using with python 2.7 or 3.0 - 3.5. I guess python 3.6 has slightly different bytecode syntax so Js2Py will not work it without modification.

**Comment by andrebrussee** [comment]
Thank you, i will try

 

Van: Piotr Dabkowski [mailto:notifications@github.com] 
Verzonden: donderdag 22 september 2016 18:24
Aan: PiotrDabkowski/Js2Py
CC: andrebrussee; Mention
Onderwerp: *SPAM* Re: [PiotrDabkowski/Js2Py] Error running basic example (#59)

 

Probably this is because you are using new Python 3.6. Try using with python 2.7 or 3.0 - 3.5. I guess python 3.6 has slightly different bytecode syntax so Js2Py will not work it without modification.
