### ISSUE TITLE
js2py.base.PyJsException: ReferenceError: print is not defined

### ISSUE THREAD

**Issue by twardoch** [PiotrDabkowski/Js2Py#71]
Playing with translation, I'm looking at how js2py plays with JS generated by emscripten from C++ files (I know there are other ways to do C++ to Python). But I keep getting `js2py.base.PyJsException: ReferenceError: print is not defined`. 

I've looked at [zopfli.js](https://github.com/imaya/zopfli.js) which is pretty straightforward. 

I've converted [zopfli.min.js](https://github.com/imaya/zopfli.js/blob/master/bin/zopfli.min.js) with js2py, see [zopfli.zip](https://github.com/PiotrDabkowski/Js2Py/files/694568/zopfli.zip)

```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zopfli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zopfli.py", line 7824, in <module>
    PyJs_anonymous_0_.callprop(u'call', var.get(u"this"))
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 874, in callprop
    return cand.call(self, args)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 1280, in call
    return Js(self.code(*args))
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/prototypes/jsfunction.py", line 29, in call
    return this.call(obj, args)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 1280, in call
    return Js(self.code(*args))
  File "zopfli.py", line 6670, in PyJs_anonymous_0_
    (var.get(u'pa') and PyJs_LONG_8_())
  File "zopfli.py", line 6669, in PyJs_LONG_8_
    return PyJsComma(PyJsComma(PyJsComma(var.get(u'Module').put(u'print', var.get(u'print')),((Js(u'undefined')!=var.get(u'printErr',throw=False).typeof()) and var.get(u'Module').put(u'printErr', var.get(u'printErr')))),var.get(u'Module').put(u'read', (var.get(u'read') if (Js(u'undefined')!=var.get(u'read',throw=False).typeof()) else PyJs_anonymous_7_))),(var.get(u'Module').get(u'arguments') or (var.get(u'Module').put(u'arguments', var.get(u'scriptArgs')) if (Js(u'undefined')!=var.get(u'scriptArgs',throw=False).typeof()) else ((Js(u'undefined')!=var.get(u'arguments',throw=False).typeof()) and var.get(u'Module').put(u'arguments', var.get(u'arguments'))))))
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 1008, in get
    return self.prototype.get(prop, throw)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 1013, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.base.PyJsException: ReferenceError: print is not defined
```

Same happens when I try to convert [harfbuzz-js](https://github.com/prezi/harfbuzz-js) using js2py, see [harfbuzz.zip](https://github.com/PiotrDabkowski/Js2Py/files/694578/harfbuzz.zip): 

```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import harfbuzz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "harfbuzz.py", line 1824, in <module>
    var.get(u'Module').put(u'print', var.get(u'print'))
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 1013, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.base.PyJsException: ReferenceError: print is not defined
>>>
```

**Comment by twardoch** [comment]
Same happens e.g. with https://github.com/richardassar/pngcrush.js

**Comment by PiotrDabkowski** [comment]
Same as in #70, print is a built-in function not present in ECMA 5.1. Even node does not have it implemented.
