### ISSUE TITLE
PyJsException: TypeError: Undefined and null dont have properties!

### ISSUE THREAD

**Issue by knordbo** [PiotrDabkowski/Js2Py#76]
I might be ambitious here but while trying to port this [svg2android](https://github.com/inloop/svg2android/tree/gh-pages/js) library to python so I can call `function generateCode(inputXml)` I get this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "all.py", line 7169, in <module>
    PyJs_anonymous_903_((var.get(u'window') if (Js(u'undefined')!=var.get(u'window',throw=False).typeof()) else var.get(u"this")), PyJs_anonymous_0_).neg()
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 861, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 1305, in call
    return Js(self.code(*args))
  File "all.py", line 7167, in PyJs_anonymous_903_
    (var.get(u'module').put(u'exports', (var.get(u'b')(var.get(u'a'), Js(0.0).neg()) if var.get(u'a').get(u'document') else PyJs_anonymous_904_)) if ((Js(u'object')==var.get(u'module',throw=False).typeof()) and (Js(u'object')==var.get(u'module').get(u'exports').typeof())) else var.get(u'b')(var.get(u'a')))
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 861, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 1305, in call
    return Js(self.code(*args))
  File "all.py", line 3393, in PyJs_anonymous_0_
    var.put(u's', PyJs_anonymous_52_(var.get(u'a')))
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 861, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 1305, in call
    return Js(self.code(*args))
  File "all.py", line 3391, in PyJs_anonymous_52_
    return PyJs_LONG_196_()
  File "all.py", line 3390, in PyJs_LONG_196_
    return PyJsComma(PyJsComma(PyJsComma(PyJsComma(PyJsComma(PyJsComma(PyJsComma(PyJsComma(PyJsComma(var.put(u'h', var.get(u'ga').put(u'compile', PyJs_anonymous_186_)),var.put(u'i', var.get(u'ga').put(u'select', PyJs_anonymous_187_))),var.get(u'c').put(u'sortStable', PyJsStrictEq(var.get(u'u').callprop(u'split', Js(u'')).callprop(u'sort', var.get(u'B')).callprop(u'join', Js(u'')),var.get(u'u')))),var.get(u'c').put(u'detectDuplicates', var.get(u'l').neg().neg())),var.get(u'm')()),var.get(u'c').put(u'sortDetached', var.get(u'ja')(PyJs_anonymous_189_))),(var.get(u'ja')(PyJs_anonymous_190_) or var.get(u'ka')(Js(u'type|href|height|width'), PyJs_anonymous_191_))),((var.get(u'c').get(u'attributes') and var.get(u'ja')(PyJs_anonymous_192_)) or var.get(u'ka')(Js(u'value'), PyJs_anonymous_193_))),(var.get(u'ja')(PyJs_anonymous_194_) or var.get(u'ka')(var.get(u'K'), PyJs_anonymous_195_))),var.get(u'ga'))
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 861, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 1305, in call
    return Js(self.code(*args))
  File "all.py", line 2466, in PyJsHoisted_ja_
    var.put(u'b', var.get(u'n').callprop(u'createElement', Js(u'div')))
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 898, in callprop
    cand = self.get(prop)
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 289, in get
    raise MakeError('TypeError', 'Undefined and null dont have properties!')
js2py.base.PyJsException: TypeError: Undefined and null dont have properties!`

Here is the JS file (merged js-files from the repo): http://pastebin.com/vnJBLGdZ

Any idea if this conversion is possible at all?

Cheers

**Comment by PiotrDabkowski** [comment]
Hey, you can see the reason straight away from the error message if you look carefully :D This method call raised the exception: `callprop(u'createElement', Js(u'div'))`. createElement is a part of DOM and DOM is not a standard feature of JavaScript, but a feature implemented by the internet browsers. I did not implement DOM. Sorry :(
