### ISSUE TITLE
NameError on anonymons function evaluation

### ISSUE THREAD

**Issue by rishikhan** [PiotrDabkowski/Js2Py#78]
f = js2py.eval_js("function(value) { var regularExpression= /^[a-zA-Z](?=.*\\d)([a-zA-Z0-9]{7,15})$/; return regularExpression.test(value); }")

causes:
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.venv/lib/python2.7/site-packages/js2py/evaljs.py", line 111, in eval_js
    return e.eval(js)
  File "/root/.venv/lib/python2.7/site-packages/js2py/evaljs.py", line 180, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/root/.venv/lib/python2.7/site-packages/js2py/evaljs.py", line 175, in execute
    exec(compiled, self._context)
  File "<EvalJS snippet>", line 2, in <module>
  File "/root/.venv/lib/python2.7/site-packages/js2py/base.py", line 861, in __call__
    return self.call(self.GlobalObject, args)
  File "/root/.venv/lib/python2.7/site-packages/js2py/base.py", line 1305, in call
    return Js(self.code(*args))
  File "/root/.venv/lib/python2.7/site-packages/js2py/host/jseval.py", line 42, in Eval
    executor(py_code)
  File "/root/.venv/lib/python2.7/site-packages/js2py/host/jseval.py", line 49, in executor
    exec(code, globals())
  File "<string>", line 9, in <module>
NameError: name 'PyJs_anonymous_0_pass' is not defined

My python version is:
>>> print (sys.version)
2.7.10 (default, Jan 25 2017, 02:28:01) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

Any idea what I'm doing wrong?

**Comment by rishikhan** [comment]
I think it's something very basic. I can't even get this simple example to work:

    f = js2py.eval_js( "function (name) {return name.length}" )

I get
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.venv/lib/python2.7/site-packages/js2py/evaljs.py", line 111, in eval_js
    return e.eval(js)
  File "/root/.venv/lib/python2.7/site-packages/js2py/evaljs.py", line 180, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/root/.venv/lib/python2.7/site-packages/js2py/evaljs.py", line 175, in execute
    exec(compiled, self._context)
  File "<EvalJS snippet>", line 2, in <module>
  File "/root/.venv/lib/python2.7/site-packages/js2py/base.py", line 861, in __call__
    return self.call(self.GlobalObject, args)
  File "/root/.venv/lib/python2.7/site-packages/js2py/base.py", line 1305, in call
    return Js(self.code(*args))
  File "/root/.venv/lib/python2.7/site-packages/js2py/host/jseval.py", line 42, in Eval
    executor(py_code)
  File "/root/.venv/lib/python2.7/site-packages/js2py/host/jseval.py", line 49, in executor
    exec(code, globals())
  File "<string>", line 8, in <module>
NameError: name 'PyJs_anonymous_0_pass' is not defined

**Comment by rishikhan** [comment]
Upon further investigation, the error seems to stem from the anonymous function. If I do:

    f = js2py.eval_js("function necessary_name(value) { var regularExpression= /^[a-zA-Z](?=.*\\d)([a-zA-Z0-9]{7,15})$/; return regularExpression.test(value); }")

This works and f("test1234") is True witch f("abc") is false.

It seems anonymous function definitions are broken in my version (which I installed today in python 2.7.10)

**Comment by PiotrDabkowski** [comment]
Nice catch, anonymous function are broken if they are a standalone expression. If you put its definition in brackets it will work. Or even  
`f = js2py.eval_js("y =function(value) { var regularExpression= /^[a-zA-Z](?=.*\\d)([a-zA-Z0-9]{7,15})$/; return regularExpression.test(value); }")`

I will fix it now.

**Comment by PiotrDabkowski** [comment]
By the way, even if you try running your example in Node.js it will also fail. Try running this in any javascript runtime:

`eval("function(value) { var regularExpression= /^[a-zA-Z](?=.*\\d)([a-zA-Z0-9]{7,15})$/; return regularExpression.test(value); }")`

You will get a syntax error, because there is no such thing allowed as a standalone function expression.
So now I don't know how to fix it. I can make it work for convenience, but that would be inconsistent with JavaScript specs. Another option would be to raise a more informative syntax error just like node.js or v8 do.

**Comment by PiotrDabkowski** [comment]
I chose to simply allow it. Fixed in c1442f1a43958fec997f8cc272100c1ad18dc0f6

**Comment by rishikhan** [comment]
It's also the example on the pypi page :)

**Comment by PiotrDabkowski** [comment]
Woops, quite unfortunate to put invalid JS as the only example on the pypi page :)
