### ISSUE TITLE
OverflowError: long int too large to convert to int

### ISSUE THREAD

**Issue by CageFreedom** [PiotrDabkowski/Js2Py#83]
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    from test1 import test1
  File "test1.py", line 832, in <module>
    var.get(u'setMaxDigits')(Js(20.0))
  File "C:\Python27\lib\site-packages\js2py-0.43-py2.7.egg\js2py\base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "C:\Python27\lib\site-packages\js2py-0.43-py2.7.egg\js2py\base.py", line 1345, in call
    return Js(self.code(*args))
  File "test1.py", line 246, in PyJsHoisted_setMaxDigits_
    var.put(u'ZERO_ARRAY', var.get(u'Array').create(var.get(u'maxDigits')))
  File "C:\Python27\lib\site-packages\js2py-0.43-py2.7.egg\js2py\base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "C:\Python27\lib\site-packages\js2py-0.43-py2.7.egg\js2py\base.py", line 1345, in call
    return Js(self.code(*args))
  File "C:\Python27\lib\site-packages\js2py-0.43-py2.7.egg\js2py\constructors\jsarray.py", line 5, in Array
    if len(arguments)==0 or len(arguments)>1:

**Comment by PiotrDabkowski** [comment]
Could you please paste the full traceback?
