### ISSUE TITLE
Invalid syntax generated

### ISSUE THREAD

**Issue by ysangkok** [PiotrDabkowski/Js2Py#89]
```
$ wget http://copy.sh/v86/build/v86_all.js
$ python3
>>> import js2py
>>> js2py.translate_file("v86_all.js","v86.py")
>>> import v86
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/janus/Skrivebord/v86/v86.py", line 1904
    var.put('a', Js(1.0).neg())
      ^
SyntaxError: invalid syntax
```

The code looks like:
```
                    class JS_CONTINUE_LABEL_61(Exception): pass
                    class JS_BREAK_LABEL_61(Exception): pass
                    try:
                        #for JS loop
                        var.put('a', var.get('a').get('target'))
                        while var.get('a').get('parentNode'):
                            try:
                                if PyJsStrictEq(var.get('a'),(var.get('b') or var.get('document').get('body'))):
                                    var.put('a', Js(0.0).neg())
                                    raise JS_BREAK_LABEL_61("Breaked")
                                var.put('a', var.get('a').get('parentNode'))
                            
                            var.put('a', Js(1.0).neg()) # error is here
                            except JS_CONTINUE_LABEL_61:
                                pass
                    except JS_BREAK_LABEL_61:
                        pass
```

**Comment by ysangkok** [comment]
Closing since I stopped using this project.
