### ISSUE TITLE
Python 2.7 support broken

### ISSUE THREAD

**Issue by worstperson** [PiotrDabkowski/Js2Py#95]
```
[user@ARCH-PC ~]$ python2
Python 2.7.14 (default, Sep 20 2017, 01:25:59) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import js2py
>>> context = js2py.EvalJs()
js2py/constructors/time_helpers.py:10: UserWarning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time')
>>> js2py.eval_js('var a = 0')                 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "js2py/evaljs.py", line 113, in eval_js
    return e.eval(js)
  File "js2py/evaljs.py", line 182, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "js2py/evaljs.py", line 175, in execute
    code = translate_js(js, '', use_compilation_plan=use_compilation_plan)
  File "js2py/translators/translator.py", line 70, in translate_js
    return HEADER + translating_nodes.trans(parsed)  # syntax tree to python code
  File "js2py/translators/translating_nodes.py", line 120, in trans
    return node(**ele)
  File "js2py/translators/translating_nodes.py", line 509, in Program
    code = ''.join(trans(e) for e in body)
  File "js2py/translators/translating_nodes.py", line 509, in <genexpr>
    code = ''.join(trans(e) for e in body)
  File "js2py/translators/translating_nodes.py", line 120, in trans
    return node(**ele)
TypeError: ExpressionStatement() got an unexpected keyword argument 'comments'
>>>
```

The problem seems to start back in this commit: https://github.com/PiotrDabkowski/Js2Py/commit/718a7d1f9c8f044d8b40074a996b20555555629b

Thanks for looking!

**Comment by PiotrDabkowski** [comment]
Hmm, that's strange because everything works fine for me. Try reinstalling js2py and later 
`pip install js2py`
to get version 0.50. Let me know if it helps!

**Comment by worstperson** [comment]
So used to just dropping dependencies into the working directory that it didn't even cross my mind, sorry to waste your time on something so trivial.

Excited to throw some code at the new VM feature when I get home. Thanks again!

**Comment by PiotrDabkowski** [comment]
Haha no worries, you did not waste my time at all :) VM is not perfect yet but it works for basic stuff + is able to execute JS about 5 times faster than the translator.

**Comment by PiotrDabkowski** [comment]
Also the VM is still quite hard to access so to use the VM you have to:

```
from js2py.internals import seval
seval.eval_js_vm(code)
```

**Comment by evandrocoan** [comment]
I am getting this warning:
`
.tox/py27/lib/python2.7/site-packages/js2py/constructors/time_helpers.py:10: UserWarning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time')
`

I think I am already up-to-date:
`
py27 installed: Js2Py==0.59,lark-parser==0.6.5,pyjsparser==2.5.2,pytz==2018.7,six==1.12.0,tzlocal==1.5.1
`

```
$ tox -e py27
GLOB sdist-make: /cygdrive/f/SublimeText/Data/Packages/pushdownparser/setup.py
py27 recreate: /cygdrive/f/SublimeText/Data/Packages/pushdownparser/.tox/py27
py27 installdeps: -rnearley-requirements.txt
py27 inst: /cygdrive/f/SublimeText/Data/Packages/pushdownparser/.tox/.tmp/package/1/lark-parser-0.6.5.zip
py27 installed: Js2Py==0.59,lark-parser==0.6.5,pyjsparser==2.5.2,pytz==2018.7,six==1.12.0,tzlocal==1.5.1
py27 run-test-pre: PYTHONHASHSEED='3455884671'
py27 runtests: commands[0] | git submodule sync -q
py27 runtests: commands[1] | git submodule update --init
py27 runtests: commands[2] | python -m tests
........sssssss...s.......ss.s...s.......s.s...........s.............................s......ss..s.......s..................................................ss..s.......s.........................s...s..........ss............s......s...s.......s.............................ss...................s...s.......s.....................
/cygdrive/f/SublimeText/Data/Packages/pushdownparser/.tox/py27/lib/python2.7/site-packages/js2py/constructors/time_helpers.py:10: UserWarning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time')
..........................
----------------------------------------------------------------------
Ran 352 tests in 41.976s

OK (skipped=37)
__________________________________________________________________________ summary ___________________________________________________________________________
  py27: commands succeeded
  congratulations :)
```
Project link: https://github.com/evandrocoan/pushdownparser/

**Comment by pannal** [comment]
I still have this issue with Py2.7:
`TypeError: ExpressionStatement() got an unexpected keyword argument 'comments'`

Data starts with:
```
{'body': [{'type': u'ExpressionStatement', 'expression': {'operator': u'=', 'right': {'type': u'CallExpression', 'callee': {'type': u'Identifier', 'name': u'eval', 'comments': []}, 'arguments': [{'raw': None, 'type': u'Literal', 'comments': [], 'value': u'
```
